dist: xenial
language: python
python: 3.7
install:
- pip install -r requirements.txt
- python setup.py install
script: pytest
addons:
  ssh_known_hosts:
  - 13.58.241.38
deploy:
  provider: script
  skip_cleanup: true
  script: ssh -i deploy_rsa ubuntu@13.58.241.38 'source /home/ubuntu/cicd_practice3/scripts/deploy.sh'
before_deploy:
- openssl aes-256-cbc -K $encrypted_d4fe774d01e8_key -iv $encrypted_d4fe774d01e8_iv
  -in deploy_rsa.enc -out deploy_rsa -d
